#!/usr/bin/env ruby

require 'linkeddata'
require 'yaml'
require 'bagit'
require 'docopt'
require './mapping_methods.rb'

include MappingMethods

doc = <<DOCOPT
ContentDM to BagIt

Consumes a directory of ContentDM collections and converts them into
bags.

Usage:
  #{__FILE__} [--skip] DIR [TARGET]
  #{__FILE__} -h | --version

Options:
  -s --skip     Skip missing fields.
  -h --help      Show this help screen.
  -v --version   Show version.

DOCOPT

@missing_fields = []
@mappings = YAML.load_file('mapping.yml')
@namespaces = {}
@mappings['namespaces'].each do |ns, base_uri|
  @namespaces[ns] = RDF::Vocabulary.new(base_uri)
end
@skip = ['unknown', 'n/a']

def create_graphs(file)
  graphs = []
  graph = RDF::Graph.new
  File.readlines(file).each do |ln|
    tag = ln.match(/^\s*<([a-z]+)>/)
    next if tag.nil? or tag[1] == 'record' or tag[1] == 'records'
    tag = tag[1]
    ln.slice!("<#{tag}>")
    ln.slice!("<\/#{tag}>")
    ln = ln.strip
    bnode = RDF::Node.new
    begin
      if @mappings['mappings'][tag.to_s].include? 'method' and not (ln == nil or ln == '')
        graph << send(@mappings['mappings'][tag.to_s]['method'].to_sym, bnode, ln) unless @skip.include? ln.downcase
      else
        ns, term = @mappings['mappings'][tag.to_s].split(':') unless (ln == nil or ln == '')
        graph << RDF::Statement.new(bnode, @namespaces[ns][term], ln) unless @skip.include? ln.downcase
      end
      
    rescue NoMethodError => e
      @missing_fields << tag unless @missing_fields.include? tag
    end

    if tag == 'dmrecord'
      graphs << set_subject(graph, RDF::URI("http://example.org/ns/#{ln}")) unless graph.empty?
      graph = RDF::Graph.new
      bnode = RDF::Node.new
    end
  end
  graphs
end

def set_subject(graph, subject)
  graph.each_statement do |statement|
    if statement.subject.node?
      graph.delete(statement)
      graph << RDF::Statement.new(subject, statement.predicate, statement.object)
    end
  end
  graph
end

def write_desc_metadata(graph, bag)
  RDF::Writer.open("descMetadata.nt", :format => :ntriples) do |writer|
    writer << graph
  end
  bag.add_tag_file('descMetadata.nt', 'descMetadata.nt')
end

def add_content_file(graph, bag)
  begin
    query = RDF::Query.new do
      pattern [:subject, RDF::URI('http://tom.oregonstate.edu/full'), :full]
    end
    fname = query.execute(graph).first[:full].to_s.split('\\')[-1].gsub(/^1_/, '')
    bag.add_file('content.tif', File.join('..', 'braceros-tiffs', query.execute(graph).first[:full].to_s.split('\\')[-1].gsub(/^1_/, '')))
  rescue NoMethodError => e
  rescue => e
    puts e
  end
end

def make_bag(dir, graph, subject)
  bag = BagIt::Bag.new(File.join(dir, File.basename(subject)))
  write_desc_metadata(graph, bag)
  add_content_file(graph, bag)
  bag.tagmanifest!
  bag.manifest!
end

def make_coll_bags(dir, target, collection, *args)
  file = File.join(dir, collection, 'index', 'description', 'desc.all')
  col_dir = FileUtils.mkdir_p(File.join(target, collection))

  graphs = create_graphs(file)
  if @missing_fields.empty? or @opts['--skip']
    graphs.each do |graph|
      subject = ''
      graph.each_statement do |s|
        subject = s.subject if s.subject.start_with? 'http://example.org/ns/'
      end
      make_bag(col_dir, graph, subject)
    end
  else
    puts "Missing fields, not writing bags for #{collection}. Add fields to mapping.yml, or use --skip flag."
  end
end

def make_all_bags(dir, target)
  target = FileUtils.mkdir_p(target)
  Dir.foreach(dir) do |collection|
    next if collection == '.' or collection == '..'
    make_coll_bags(dir, target, collection)
  end
end

begin
  @opts = Docopt::docopt(doc, version: 'cdm2bag 0.0.2')
  make_all_bags(@opts['DIR'], @opts['TARGET'] || 'bags')
  puts @missing_fields unless @missing_fields.empty?
rescue Docopt::Exit => e
  puts e.message
end
